version: '3.1'

volumes:
  files:
    driver: local
  mariadb:
    driver: local
  backup:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    container_name: owncloud_web
    image: webhippie/mariadb:latest
    env_file:
      - ../.env
    # image: owncloud/server:${OWNCLOUD_VERSION}
    restart: always
    ports:
      - ${OWNCLOUD_HTTP_PORT}:80
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=owncloud_db
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=owncloud_redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data
    networks:
      reverse_proxy:
      owncloud_backend:

  db:
    image: webhippie/mariadb:latest
    restart: 'no'
    container_name: owncloud_db
    env_file:
      - ../.env
    ports:
      - 3306:3306
    environment:
      - MARIADB_MAX_ALLOWED_PACKET=128M
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/var/lib/mysql
      # - mariadb:/var/lib/mysql
      - backup:/var/lib/backup
    networks:
      owncloud_backend:

  redis:
    image: webhippie/redis:latest
    container_name: owncloud_redis
    restart: always
    environment:
      - REDIS_DATABASES=1
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis:/var/lib/redis
    networks:
      owncloud_backend:
networks:
  owncloud_backend:
  reverse_proxy:
